### ISSUE TITLE
Improve logging capability

### ISSUE THREAD

**Issue by ChristianBeer** [MersenneForum/MersenneForumAliquot#6] opened 2017-12-10 19:27 UTC
I was just reading up on the python logging module. Here is what I would like to discuss.

Based on the example in https://docs.python.org/3/howto/logging-cookbook.html#multiple-handlers-and-formatters I would like to have a format with a timestamp on each line and the severity levels used to output to two targets. The 'INFO' and higher messages should go in a file (that is rotated weekly) and 'ERROR' and higher should be send via email (at the end of the script preferably). Sending emails is done via a local postfix server and doesn't require authentication. I would like to have an easy way to set the file severity to 'DEBUG' to get finer grained information (such as how priorities changed). An email should be triggered for merges, terminations and other abnormal terminations that prevent the scripts from proper restarting the next time it is run.

The logfile should go into log/ not into scripts/ and named like the python script (`scripts/allseq.py` would write to `log/allseq.log`).

I think something like the following config would be a nice start:
```
LOGGER = logging.getLogger()
LOGGER.setLevel(logging.DEBUG)
fh = logging.TimedRotatingFileHandler('../log/allseq.log', 'W0')
fh.setLevel(logging.INFO) # change here to also log DEBUG to file
# see https://gist.github.com/anonymous/1379446 for BufferingSMTPHandler (not tested)
mh = BufferingSMTPHandler(MAILHOST, FROM, TO, SUBJECT, 10)
mh.setLevel(logging.ERROR)
# create formatter and add it to the handlers
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
mh.setFormatter(formatter)
fh.setFormatter(formatter)
# add the handlers to logger
LOGGER.addHandler(ch)
LOGGER.addHandler(fh)
```

https://github.com/MersenneForum/MersenneForumAliquot/blob/77b831007fdc5d37d52fd5470e1e551cb0cc1378/scripts/allseq.py#L75

**Comment by dubslow** [comment] 2017-12-11 01:06
In my original massive PM to you, I had indeed mentioned the logging as the biggest regression in functionality, including such links as you've already found :) I'm already working on one more refactoring that will include configuration file functionality, and that will include the logging config in [`dict`](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig) form (as opposed to programmatic form like you have here). Should be only a day or two to get that approximately working. I'll base my first logging config on what you have suggested here.

**Comment by ChristianBeer** [comment] 2017-12-11 15:24
I'm trying to disentangle the issues from the big PM's into smaller issues here to better discuss them if needed. I also saw the `dict` config but deemed it too advanced for the moment. If you find that better it is fine with me as long as the end result is the same functionality.

**Comment by dubslow** [comment] 2017-12-12 02:52
I'm trying to reduce duplication of settings across several scripts, as is currently the case, so most of this logging stuff should definitely be in the config file, which kinda limits doing it programmatically. I'll try and work it up by Friday, as you mentioned. And I'm happy to move most of our conversations to issues here, as you say it is indeed much easier to manage here

**Comment by dubslow** [comment] 2017-12-12 05:21
Why timed rotating instead of size rotating?

**Comment by dubslow** [comment] 2017-12-12 10:52
I'm leaving the email for another day or two, I'm rather annoyed that the `logging` module of the standard library includes an `SMTPHandler` and a `BufferedHandler` but not a `BufferedSMTPHandler`. Batteries included, indeed.

Let me know what you think so far. The console handler can be ignored in crontabs by just redirecting to /dev/null, because otherwise it's quite useful for me.

**Comment by ChristianBeer** [comment] 2017-12-13 19:56
> Why timed rotating instead of size rotating?

When looking at older entries in logfiles I want to be able to quickly find it by looking at the filename. I usually go back in time to see what happened earlier or what happened last week at the same time. Using size rotation would mean that I would need to look at the content of the file to see if the timerange I'm looking for is in there. I know I could use the timestamps of the files but that means I need to look through a long list of files just to find out where the log from last week is instead of using the actual date in the filename (when using daily rotation). Using a weekly rotation is kind of a compromise to not have lots of small files for every day.

> I'm leaving the email for another day or two, I'm rather annoyed that the logging module of the standard library includes an SMTPHandler and a BufferedHandler but not a BufferedSMTPHandler. Batteries included, indeed.

Looks good so far. I also wondered about the `BufferedSMTPHandler`, what about the gist I linked to? Can't you just copy that?

**Comment by dubslow** [comment] 2017-12-14 14:26
I've been reading docs and baking the design in my head, and I'm going to roll my own class that's functionally similar but under the hood a bit different from the gist you pointed me to. (In a series of googlings on the topic, that gist indeed seems to be the "standard", which suffers from some problems I have with the underlying `logging.BufferedHandler` class, namely that it insists on testing the level for each record to see if it should flush, and also insisting on a maximum buffer capacity. So I'm just going to roll it all myself, having reviewed the stdlib module's code I'm confident in its design and thus in my own subclass against its design. 

The biggest problem I foresee is configuring my local `postfix` for testing. In any case, keep an eye on `dev` over the next few days.

**Comment by dubslow** [comment] 2017-12-14 17:22
Tweaking which events are worthy of emails is definitely available to you. If necessary, the `logging` module supports adding additional levels to its 1D scale of log levels, so if you think it's necessary we could, e.g., add a level like `notable` between `warning` and `error`, so that warnings aren't emailed, or something along those lines. Let me know, or even make the changes yourself if you so desire

**Comment by ChristianBeer** [comment] 2017-12-23 09:10
The logging changes are live since 1 day and so far working nice. The `mfaliquot.BufferingSMTPHandler` also seems to work nicely. It seems that the current loglevels `INFO` for files and `WARNING` for emails is sufficient. I'll keep this issue open until the first rotation happens.

**Comment by dubslow** [comment] 2018-01-05 00:44
How was the file rotation?

**Comment by ChristianBeer** [comment] 2018-01-05 14:11
In general it seems to work. The only thing that I noticed is that the files are called like this:
```
allseq.log             allseq.log.2017-12-26  cron-reservations.log  reservations.log.2017-12-19  update_priorities.log             update_priorities.log.2017-12-19
allseq.log.2017-12-19  cron-allseq.log        reservations.log       reservations.log.2017-12-26  update_priorities.log.2017-12-05  update_priorities.log.2017-12-26
```
It seems that the date added to the file is the tuesday. From the Content it seems that the time based rotation happens at the end of the day that is specified. I'm going to switch from `W0` to `W6` so I always have a full week in a single file.

**Comment by dubslow** [comment] 2018-01-08 18:34
Oh yes, especially with the rotation tweaks and the tweaks I just made to reduce verbosity, I'm closing the issue as complete until or unless there's some further problem... which I think there isn't?

:)

**Closed by dubslow** 2018-01-08 18:34 UTC
Labels: enhancement
